#!/bin/sh
set -e
# Automatically added by dh_makeshlibs
case "$1" in
    remove|purge)
    dpkg-divert --package live-isn --rename --remove /usr/bin/xfce4-session-logout
    dpkg-divert --package live-isn --rename --remove /usr/bin/mkdiskimage
#    dpkg-divert --package live-isn --rename --remove /usr/bin/startx
    dpkg-divert --package live-isn --rename --remove /etc/initramfs-tools/initramfs.conf
#    dpkg-divert --package live-isn --rename --remove @@@@
    dpkg-divert --package live-isn --rename --remove /etc/skel/.bashrc
    ;;
    
    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)


        ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 0

esac




# End automatically added section
