#!/bin/sh
set -e
# Automatically added by dh_makeshlibs
case "$1" in
    remove|purge)
    dpkg-divert --package xbase-agreg --rename --remove /usr/X11R6/bin/startx
    dpkg-divert --package xbase-agreg --rename --remove /usr/bin/startx
               
    ;;
    
    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)


        ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 0

esac




# End automatically added section
